import { StateProvider } from "@/context/StateContext";

import AuthModal from "@/components/AuthModal";
import Footer from "@/components/pages/Footer";
import Navbar from "@/components/pages/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StateProvider>
          <div className="flex flex-col justify-between h-screen relative">
            <Navbar />
            <div className="mb-auto w-full mx-auto">
              {children}
              <AuthModal />
            </div>
            <Footer />
          </div>
        </StateProvider>
      </body>
    </html>
  );
}
