export const reducerCases = {
  TOGGLE_LOGIN_MODAL: "TOGGLE_LOGIN_MODAL",
  TOGGLE_SIGNUP_MODAL: "TOGGLE_SIGNUP_MODAL",
  CLOSE_LOGIN_SIGNUP_MODAL: "CLOSE_LOGIN_SIGNUP_MODAL",
  SET_USER_INFO: "SET_USER_INFO",
};
